name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Backend

      - name: Install Backend
        working-directory: backend
        run: npm ci

      - name: Backend Typecheck
        working-directory: backend
        run: npm run typecheck

      - name: Backend Build
        working-directory: backend
        run: npm run build

      # Frontend

      - name: Install Frontend
        working-directory: frontend
        run: npm ci

      - name: Frontend Lint
        working-directory: frontend
        run: npm run lint

      - name: Frontend Build
        working-directory: frontend
        run: npm run build

  docker:

    needs: checks

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend Image

      - name: Build Backend Image
        run: |
          docker build \
          -t srinandhan/backend-demo:latest \
          -t srinandhan/backend-demo:${{ github.sha }} \
          ./backend

      - name: Push Backend Latest
        run: docker push srinandhan/backend-demo:latest

      - name: Push Backend SHA
        run: docker push srinandhan/backend-demo:${{ github.sha }}

      # Frontend Image

      - name: Build Frontend Image
        run: |
          docker build \
          -t srinandhan/frontend-demo:latest \
          -t srinandhan/frontend-demo:${{ github.sha }} \
          ./frontend

      - name: Push Frontend Latest
        run: docker push srinandhan/frontend-demo:latest

      - name: Push Frontend SHA
        run: docker push srinandhan/frontend-demo:${{ github.sha }}