name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Production
        run: |
          cd /root/bluvern/devops/deployments/production
          docker compose pull
          docker compose up -d