name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment
        run: |
          pwd
          whoami
          which docker || true
          docker version || true